changed format

diff --git a/television b/television
--- a/television
+++ b/television
@@ -8,7 +8,7 @@ dep_ck () {
 }
 dep_ck "fzf" "curl" "jq" "gawk"
 
-version=2.4.1
+version=2.5.1
 main_url="https://iptv-org.github.io/iptv/channels.json"
 menu="fzf -e -i --layout=reverse --cycle --inline-info --border=${BORDER:-sharp}"
 
@@ -28,111 +28,154 @@ export favs_file=~/.cache/television_favs
 : "${favschan:=alt-f}"
 
 help() {
-  printf '%s\n' "options for ${0##*/}:"
-  printf '\033[1;33m%s \033[0m \t%s \n' " -r" "for radio"
-  printf '\033[1;33m%s \033[0m \t%s \n' " -d" "for download the m3u file"
-  printf '\033[1;33m%s \033[0m \t%s \n' " -e" "for channels focused on spanish language"
-  printf '\033[1;33m%s \033[0m \t%s \n' " -f" "to choose from favorites"
-  printf '\033[1;33m%s \033[0m \t%s \n' " -E" "to edit the favorites file"
-  printf '\033[1;33m%s \033[0m \t%s \n' " -u" "for update this script"
-  printf '\033[1;33m%s \033[0m \t%s \n' " -v" "for print version"
-  printf '%s\n' "keybinds"
-  printf '%s\t%s\n' " ${playvid}" "for play video"
-  printf '%s\t%s\n' " ${detachplayer}" "for detaching player"
-  printf '%s\t%s\n' " ${onlyaudio}" "for play only audio"
-  printf '%s\t%s\n' " ${getlink}" "for get link"
-  printf '%s\t%s\n' " ${favschan}" "for adding channel to favorites "
+	 printf '%s\n' "options for ${0##*/}:"
+	 printf '\033[1;33m%s \033[0m \t%s \n' " -r" "for radio"
+	 printf '\033[1;33m%s \033[0m \t%s \n' " -d" "for download the m3u file"
+	 printf '\033[1;33m%s \033[0m \t%s \n' " -e" "for channels focused on spanish language"
+	 printf '\033[1;33m%s \033[0m \t%s \n' " -f" "to choose from favorites"
+	 printf '\033[1;33m%s \033[0m \t%s \n' " -E" "to edit the favorites file"
+	 printf '\033[1;33m%s \033[0m \t%s \n' " -u" "for update this script"
+	 printf '\033[1;33m%s \033[0m \t%s \n' " -v" "for print version"
+	 printf '%s\n' "keybinds"
+	 printf '%s\t%s\n' " ${playvid}" "for play video"
+	 printf '%s\t%s\n' " ${detachplayer}" "for detaching player"
+	 printf '%s\t%s\n' " ${onlyaudio}" "for play only audio"
+	 printf '%s\t%s\n' " ${getlink}" "for get link"
+	 printf '%s\t%s\n' " ${favschan}" "for adding channel to favorites "
 }
+
 _update () {
-	update="$(curl -s "https://raw.githubusercontent.com/khonsaloh/television/master/television" | diff -u "$0" -)"
+	update="$(curl -sL "https://raw.githubusercontent.com/khonsaloh/television/master/television")" || echo "Connection error"
+	update="$(printf '%s\n' "$update" | diff -u "$0" -)"
 	if [ -z "$update" ]; then
-		printf "%s\n" "Script is up to date"
+		echo "Script is up to date :)"
 	else
-		printf '%s\n' "$update" | patch "$0" - \
-			&& printf "%s\n" "Script has been updated"
+		if printf '%s\n' "$update" | patch "$0" - ; then
+			echo "Script has been updated"
+		else
+			echo "Can't update for some reason!"
+		fi
 	fi
+	exit 0
 }
+
 command -v _hide_win >/dev/null || _hide_win () {
-		vent=$(xdotool getactivewindow 2>/dev/null) \
+	vent=$(xdotool getactivewindow 2>/dev/null) \
 		&& xdotool windowunmap $vent 2>/dev/null
-			"$@"
-		xdotool windowmap $vent 2>/dev/null
+	"$@"
+	xdotool windowmap $vent 2>/dev/null
 }
+
 export -f _hide_win
 export hide=_hide_win
 
-case $1 in
-	-r)
-		url=$(curl -sl 'https://www.tdtchannels.com/lists/radio.json' \
-      | jq -r '.countries[].ambits[].channels[] | "\(.name // "N/A") \t \(.options[].url // "N/A")"' )
-		while [ "$url" ]; do
-			selection=$(printf '%s\n' "$url" \
-        | $menu --with-nth="1" -d'\t' --prompt='radio: ')
-			[ -z "$selection" ] && { tput cnorm 2>/dev/null; exit; }
-			[ $TERMUX_VERSION ] && termux-open "${selection##* }" \
-				|| { tput civis; echo "${selection%% ht*}" \
-				&& mpv "${selection##* }" --force-media-title="${selection%% ht*}"; }
-		done
-		;;
+_radio() {
+	url=$(curl -sL 'https://www.tdtchannels.com/lists/radio.json' \
+		| jq -r '.countries[].ambits[].channels[] | "\(.name // "N/A") \t \(.options[].url // "N/A")"' 2>/dev/null) \
+		|| echo "error getting data"
+	
+	while [ "$url" ]; do
+		selection=$(printf '%s\n' "$url" \
+			| $menu --with-nth="1" -d'\t' --prompt='radio: ')
+		[ -z "$selection" ] && { tput cnorm 2>/dev/null; exit; }
+		
+		[ "$TERMUX_VERSION" ] && termux-open "${selection##* }" \
+			|| { tput civis; echo "${selection%% ht*}" \
+			&& mpv "${selection##* }" --force-media-title="${selection%% ht*}"; }
+	done
+}
 
-	-d)
-		url=$(curl -Lsf 'https://raw.githubusercontent.com/iptv-org/iptv/master/README.md' \
+_download_playlist() {
+	url=$(curl -Lsf 'https://raw.githubusercontent.com/iptv-org/iptv/master/README.md' \
 		| grep -oP '(?<=code>).*(?=</code)' \
 		| $menu --prompt='television: ') \
-		&& curl -sfL $url -O ;;
+		&& curl -sfL $url -O 
+}
 
-	-f)
-		while [ -f $favs_file ]; do
+_favorites() {
+	while [ -f $favs_file ]; do
 		urls=$($menu --with-nth="1..-2" < $favs_file )
-			[ -z "$urls" ] && exit \
-				|| [ $TERMUX_VERSION ] && termux-open "${urls##* }" \
-				|| $hide mpv "${urls##* }" --force-media-title="${urls%%  *}"
-		done
-		[ ! -f $favs_file ] && printf '%s\n' "you don't have any favorites yet"
+		[ -z "$urls" ] && exit \
+			|| [ $TERMUX_VERSION ] && termux-open "${urls##* }" \
+			|| $hide mpv "${urls##* }" --force-media-title="${urls%%  *}"
+	done
+
+	[ ! -f $favs_file ] && printf '%s\n' "you don't have any favorites yet"
+}
+
+_edit_favorites() {
+	$EDITOR $favs_file 2>/dev/null || xdg-open $favs_file
+}
+
+_show_version() {
+	printf '%s\t%s\n' "${0##*/} ${version}" "powered by https://github.com/khonsaloh/television"
+}
+
+_tdt_channels () {
+	url=$(curl -Ls  'https://www.tdtchannels.com/lists/tv.json' \
+		| jq -r '.countries[].ambits[].channels[] | "\(.name // "N/A") \t \(.options[].url // "N/A")"' 2>/dev/null) \
+		|| echo "error getting data"
+	
+	while [ "$url" ]; do
+		selection=$(printf '%s\n' "$url" \
+			| $menu --delimiter="\t" --with-nth="1" --prompt='television: ')
+		[ -z "$selection" ] && exit \
+			|| $hide mpv "${selection##* }" --force-media-title="${selection%% htt*}"
+	done
+}
+
+case $1 in
+	-r)
+		_radio
+		;;
+	-d)
+		_download_playlist
+		;;
+	-f)
+		_favorites
 		;;
 	-E)
-    $EDITOR $favs_file 2>/dev/null || xdg-open $favs_file
-    ;;
+		_edit_favorites
+		;;
 	-v)
-		printf '%s\t%s\n' "${0##*/} ${version}" "powered by https://github.com/khonsaloh/television"
+		_show_version
 		 ;;
 	-e)
-		url=$(curl -Lsf  'https://www.tdtchannels.com/lists/tv.json' \
-      | jq -r '.countries[].ambits[].channels[] | "\(.name // "N/A") \t \(.options[].url // "N/A")"' )
-		while [ "$url" ]; do
-			selection=$(printf '%s\n' "$url" \
-				| $menu --delimiter="\t" --with-nth="1" --prompt='television: ')
-			[ -z "$selection" ] && exit \
-				|| $hide mpv "${selection##* }" --force-media-title="${selection%% htt*}"
-		done
+		_tdt_channels
 		;;
-	 -u)
+	-u)
 		_update
 		;;
-
-	*) [ $* ] && help ;;
+	*) 
+		[ $* ] && help
+		;;
 esac
 
 [ $* ] && exit
 
-[ ! $TERMUX_VERSION ] && channel_file=/tmp/channel_file.json || { channel_file=$HOME/.cache/channel_file.json;
-	[ -f $channel_file ] && [ $(($(date +%s) - $(date +%s -r $channel_file) )) -gt 90000 ] \
-	&& curl "$main_url" -H "accept-encoding:gzip" --compressed -o $channel_file -sL; }
-	 #write file to ram for better speed during the session
+[ ! $TERMUX_VERSION ] && channel_file=/tmp/channel_file.json || 
+	{
+		channel_file=$HOME/.cache/channel_file.json;
+		[ -f $channel_file ] && [ $(($(date +%s) - $(date +%s -r $channel_file) )) -gt 90000 ] \
+			&& curl "$main_url" -H "accept-encoding:gzip" --compressed -o $channel_file -sL;
+	}
 
-[ ! -f $channel_file ] && { curl "$main_url" -H "accept-encoding:gzip" --compressed -o $channel_file -sL \
-	|| ( printf '%s\n' "it seems you don't have an internet conection" && kill $$) }
+[ ! -f $channel_file ] \
+	&& {
+	curl "$main_url" -H "accept-encoding:gzip" --compressed -o $channel_file -sL \
+	|| { printf '%s\n' "It seems you don't have an internet connection"; exit 1; }
+	}
 
 CHANNELS=$(jq -r '.[] | "\(.name) \t \(.categories[].name // "N/A") \t \(.languages|.[0].name // "N/A") \t \(.countries|.[0].name // "N/A") \t \(.url)"' $channel_file \
-	                | gawk -v max="${COLUMN_SIZE:-80}" 'BEGIN { RS="\n"; FS=" \t " }
-                    {
-	               name = substr(gensub(/[0-9]+\.\s*(.*)/, "\\1", "g", $1),0,max/4)
-	               category = substr(gensub(/\s+> (.*)/, "\\1", "g", $2),0,max/8)
-	               languages = substr(gensub(/\s+> (.*)/, "\\1", "g", $3),0,max/8)
-	               countries = substr(gensub(/\s+> (.*)/, "\\1", "g", $4),0,70)
-	               channelUrl = substr(gensub(/\s+> (.*)/, "\\1", "g", $5),0)
-	               print name "\t|" category "\t|" languages "\t|" countries "\t" channelUrl
-	              }' | column -t -s $'\t')
+	| gawk -v max="${COLUMN_SIZE:-80}" 'BEGIN { RS="\n"; FS=" \t " }
+	{
+		name = substr(gensub(/[0-9]+\.\s*(.*)/, "\\1", "g", $1),0,max/4)
+	        category = substr(gensub(/\s+> (.*)/, "\\1", "g", $2),0,max/8)
+	        languages = substr(gensub(/\s+> (.*)/, "\\1", "g", $3),0,max/8)
+	        countries = substr(gensub(/\s+> (.*)/, "\\1", "g", $4),0,70)
+	        channelUrl = substr(gensub(/\s+> (.*)/, "\\1", "g", $5),0)
+	        print name "\t|" category "\t|" languages "\t|" countries "\t" channelUrl
+	}' | column -t -s $'\t')
 
 command -v _playvid >/dev/null || _playvid() {
 	printf '%s\n' "Fetching channel..."
@@ -144,6 +187,7 @@ command -v _detachplayer >/dev/null || _detachplayer() {
  	printf '%s\n' "Fetching channel..."
  	{ setsid -f mpv "${*##* }" --really-quiet --force-media-title="${*%%  *}" & }
 }
+
 command -v _onlyaudio >/dev/null || _onlyaudio() {
 	printf '%s\n' "Fetching channel..."
 	tput civis; printf '%s\n' "${*%%  *}"
@@ -153,17 +197,17 @@ command -v _onlyaudio >/dev/null || _onlyaudio() {
 
 _getlink() {
 	echo "${*##* }"; command -v notify-send >/dev/null && notify-send "${*##* }"
-	}
+}
 
 _favchannels () {
 	echo "$@" >> $favs_file
- }
+}
 
 _colorize() {
-  local string
-  string="${1//\[/\\033\[0;32m\[}"
-  string="${string//\]/\]\\033\[0m}"
-  printf '%b\n' "${string}"
+	local string
+	string="${1//\[/\\033\[0;32m\[}"
+	string="${string//\]/\]\\033\[0m}"
+	printf '%b\n' "${string}"
 }
 
 HEADER_TV="$(_colorize "[${playvid}] Play channel [Escape] Exit
@@ -180,4 +224,4 @@ printf '%s\n' "${CHANNELS}" | $menu --with-nth="1..-2" \
 	--bind "$detachplayer:execute(_detachplayer {})" \
 	--bind "$favschan:execute(_favchannels {})" \
 	--prompt "Search: " \
-  --header="${HEADER_TV}" -q "${*:-}" 
+	--header="${HEADER_TV}" -q "${*:-}"
