remaster

diff --git a/television b/television
--- a/television
+++ b/television
@@ -1,71 +1,124 @@
-#!/bin/sh
-dummy="./.cache"
-[ -z "$dummy" ] && mkdir -p "$dummy"
+#!/usr/bin/env bash
 
-# comprobacion de dependencias
 dep_ck () {
 	for dep in "$@"; do
-		command -v "$dep" 1>/dev/null || { printf "$dep not found. Please install it. ($dep no encontrado. Por favor instalalo) .\\n" ; exit 2; }
+		command -v "$dep" 1>/dev/null \
+			|| { printf "$dep not found. Please install it. ($dep no encontrado. Por favor instalalo) .\\n"; exit 2; }
 	done
 }
-dep_ck "tr" "sed" "xdo" "curl" "printf" "jq" "youtube-dl" "mpv" "dmenu" "awk" "grep"
+dep_ck "sed" "xdotool" "curl"  "jq" "youtube-dl" "mpv" "dmenu" "awk" "grep"
+
+y="\033[1;33m"
+re="\033[0m"
+table=1
+fzf=0
+main_url="https://iptv-org.github.io/iptv/channels.json"
+
+help() {
+printf "opciones son:\\n"
+printf '%b' "${y}-es${re}\\tpara canales en español\\n"
+printf '%b' "${y}-r${re}\\tpara radio\\n"
+printf '%b' "${y}-d${re}\\tpara descargar el archivo m3u\\n"
+printf '%b' "${y}-l${re}\\tpara listas de reproduccion, (pulsando p se obtiene un menu)\\n"
+printf '%b' "${y}-le${re}\\tpara listas de reproduccion en español exclusivamente, (pulsando p se obtiene un menu)\\n"
+printf '%b' "${y}-L${re}\\tpara solo obtener el link\\n" 
+}
 
 case $1 in
-	-es|es) a="$(curl -sf 'https://www.tdtchannels.com/lists/tv.m3u' | grep -v '#')" && vent=$(xdo id) && xdo hide $vent
+	-es|es) 
+		a="$(curl -Lsf 'https://www.tdtchannels.com/lists/tv.m3u' | grep -v '#')" \
+			&& vent=$(xdotool getactivewindow) && xdotool windowunmap $vent
 		while true; do
 			b="$(echo "$a" | dmenu -i -l 30 -sb '#661a1a' -p 'television española')"
-			[ -z "$b" ] && xdo show $vent && exit || mpv --really-quiet \
-				--user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36" "$b" #>/dev/null 2>&1
+			[ -z "$b" ] && xdotool windowmap $vent && exit || mpv --really-quiet "$b" 
 		done &
 		;; #individuales
 	
-	-radio|-r) a="$(curl -4 -sf 'https://www.tdtchannels.com/lists/radio.m3u8' | grep -v '#')"
+	-r) 
+		a="$(curl -Lsf 'https://www.tdtchannels.com/lists/radio.m3u8' | grep -v '#')"
 		while true; do
 			b="$(echo "$a" | dmenu -i -l 30 -sb '#661a1a' -p 'television española')"
 				[ -z "$b" ] && exit || mpv --really-quiet "$b" 2>/dev/null
 		done
 		;;
 	
-	--help|-h|h) printf "opciones son -es, -radio -r , --descargar, --lista -l, -li\\n" ;;
-	
-	-d|--descargar) a=$(curl -sf 'https://raw.githubusercontent.com/iptv-org/iptv/master/README.md'  |
+	-d) 
+		url=$(curl -Lsf 'https://raw.githubusercontent.com/iptv-org/iptv/master/README.md' |
 		awk '/http/' | grep -o -P '(?<=code>).*(?=</code)' | sed 's/<.*//' |
-		dmenu -i -l 30 -sb '#661a1a' -p 'television') && b=$(curl -4 -sf "$a" | grep -v '#') && mpv --really-quiet $b ;;
+		dmenu -i -l 30 -sb '#661a1a' -p 'television') && curl -sfL $url -o $PWD/"$(echo $url \
+		| awk -F'/' '{print $NF}')" ;;
 	
-	--lista|-l|l) b="$(curl -sf https://raw.githubusercontent.com/iptv-org/iptv/master/README.md | awk '/http/' |
-		grep -o -P '(?<=code>).*(?=</code)' | sed 's/<.*//')" 
-		vent=$(xdo id) && xdo hide $vent
+	-l|l) 
+		curl -Lsf https://raw.githubusercontent.com/iptv-org/iptv/master/README.md | grep 'http' \
+			| grep -o -P '(?<=code>).*(?=</code)' | sed 's/<.*//' >/tmp/iptv_categories
 		while true; do
-			c="$(echo "$b" | dmenu -i -l 30 -p television  -sb '#7a998d' -nb '#262626' )"
-			[ -z "$c" ] && xdo show $vent && exit
-			mpv --really-quiet --script=./plugins/playlistmanager.lua --use-filedir-conf=yes \
-				 --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:53.0) Gecko/20100101 Firefox/53.0" "$c"
-		done & 
+			rec="$(cut -f2- /tmp/iptv_categories | awk -F'/' '{print $(NF-1),$NF}' \
+				| sort | fzf | rev | cut -c5- | cut -d' ' -f1 | rev)"
+			[ -n "$rec" ] && vent=$(xdotool getactivewindow) && xdotool windowunmap $vent
+			url=$(grep "$rec.m3u$" /tmp/iptv_categories)
+			[ -z "$rec" ] && exit
+			mpv --script=./plugins/playlistmanager.lua --use-filedir-conf=yes "$url"
+			xdotool windowmap $vent
+		done 
+		;;
+	-le|le)
+		url=$(curl -Lsf  'https://www.tdtchannels.com/lists/tv.w3u' \
+			| jq -r '["CANAL","ENLACE"], ["----","------"], (.groups[].stations[] | [.name, .url]) | @csv')
+		[ -n "$url" ] && vent=$(xdotool getactivewindow) && xdotool windowunmap $vent
+		while true; do
+			menu=$(printf '%s' "$url\n" | column -t -s',' | tr -d '"' \
+				| dmenu -i -l 20 -p television -sb '#661a1a' -fn 'mono' \
+				| awk '{print $NF}')
+			[ -z "$menu" ] && xdotool windowmap $vent && exit \
+				|| mpv "$menu"
+
+		done
+		;;
+	-L)
+
+		url=$(curl -Lsf 'https://iptv-org.github.io/iptv/channels.json' \
+			| jq -r '["CANAL","ENLACE"], ["----","------"], (.[] | [.name, .url]) | @csv')
+		printf '%b' "$url\n" | column -t -s',' | tr -d '"' \
+			| dmenu -i -l 30 -fn 'mono' -p 'elige enlace: ' | awk '{print $NF}'
+
+		;;
+
+	 -G) 
+		a="$(curl -Lsf https://iptv-org.github.io/iptv/channels.json \
+	 	| jq -r '["CANAL","ENLACE"], ["----","------"], (.[] | [.name, .url]) | @csv' \
+		| dmenu -i -l 30 | awk '{print $NF}')"
+		[ -n "$a" ] && ffmpeg -i "$a" -c copy /tmp/out.ts; mpv /tmp/out.ts
 		;;
 	
-	--li|-li|li) mpv --script=./plugins/playlistmanager.lua --use-filedir-conf=yes --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:53.0) Gecko/20100101 Firefox/53.0" \
-		$(curl -sf  'https://www.tdtchannels.com/lists/tv.w3u' | jq '.groups[].stations[] | "\(.name) \(.url)"' | dmenu -i -l 30 -p television -sb '#661a1a' ) >/dev/null & ;;
+	*) [ -n "$1" ] && help ;;
 esac
-#fzf << EOF
-#descargar/actualizar lista de reproduccion
-#EOF
-#a=$(curl -sf https://raw.githubusercontent.com/iptv-org/iptv/master/README.md | awk '/http/' | grep -o -P '(?<=code>).*(?=</code)' | sed 's/<.*//'  | dmenu -i -l 30 -p television -sb '#661a1a' ) && mpv $a
+
 
 [ -n "$1" ] && exit
 
-a="$(curl -sf https://iptv-org.github.io/iptv/channels.json | jq '.[] | "\(.name) \(.url)"' | tr -d '"')"
 
-while true; do
-	b="$(echo "$a" | dmenu -i -l 30 -sb '#661a1a' -p 'canal' | awk '{print $NF}')" && [ -z "$b" ] && exit
-	mpv --really-quiet --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:53.0) Gecko/20100101 Firefox/53.0" "$b" #>/dev/null 2>&1 #individuales
-	#[ -z "$b" ] && exit
-done &
+CHANNELS_LIST=$(curl -sL "$main_url" \
+	| jq -r '.[] | "\(.name) \t \(.category // "N/A") \t \(.languages|.[0].name // "N/A") \t \(.countries|.[0].name // "N/A") \t \(.url)"' |\
+	                gawk -v max="${COLUMNS:-80}" 'BEGIN { RS="\n"; FS=" \t " }
+                    {
+	               name = substr(gensub(/[0-9]+\.\s*(.*)/, "\\1", "g", $1),0,max/4)
+	               category = substr(gensub(/\s+> (.*)/, "\\1", "g", $2),0,max/8)
+	               languages = substr(gensub(/\s+> (.*)/, "\\1", "g", $3),0,max/8)
+	               countries = substr(gensub(/\s+> (.*)/, "\\1", "g", $4),0,70)
+	               channelUrl = substr(gensub(/\s+> (.*)/, "\\1", "g", $5),0)
+	               print name "\t|" category "\t|" languages "\t|" countries "\t" channelUrl
+	              }' | column -t -s $'\t' \
 
-#a="$(curl -4 -sf https://iptv-org.github.io/iptv/channels.json | jq '.[] | "\(.name) \(.url)"' | tr -d '"' \
-#| dmenu -i -l 30 -sb '#661a1a' -p 'canal' -fn 'Ubuntu Mono' | awk '{print $NF}')" && [ -n "$a" ] &&
-#mpv --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:53.0) Gecko/20100101 Firefox/53.0" $opt "$a" 2>&1 /dev/null & #individuales
+)
 
+_play() {
+	printf '%s\n' "Fetching channel, please wait..."
+	vent=$(xdotool getactivewindow) && xdotool windowunmap $vent \
+		&& mpv "${*##* }" --realy-quiet --force-media-title="${*%%  *}" ; xdotool windowmap $vent
+	}
 
-#a="$(curl -4 -sf https://iptv-org.github.io/iptv/channels.json | jq '.[] | "\(.name) \(.url)"' | tr -d '"' \
-#| fzf --reverse --cycle | awk '{print $NF}')" && [ -n "$a" ] &&
-#mpv --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:53.0) Gecko/20100101 Firefox/53.0" $opt "$a" 2>&1 /dev/null & #individuales
+export -f _play
+SHELL="$(command -v bash)"		     
+ printf '%s\n' "${CHANNELS_LIST}" | fzf -e -i --reverse --cycle --with-nth="1..-2"\
+           --bind "enter:execute(_play {})"\
+           --header="Select channel (press Escape to exit)" -q "${*:-}" 
